<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Sample Application</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: left;
            color: #aaa;
            font-size: 18px;
        }
        h1 {
            color: black;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 40px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>
<body>
<h1>Demo Application</h1>
<div>Post Details</div>
<?php if(!empty($post) && is_array($post)) : ?>
    <table border="1">
        <tr>
            <td>Title : </td>
            <td><?= htmlspecialchars($post['title']); ?></td>
        </tr>
        <tr>
            <td>Detailed Description : </td>
            <td><?= htmlspecialchars($post['long_text']); ?></td>
        </tr>
        <tr>
            <td>Date Created : </td>
            <td><?= date('F j, Y', strtotime($post['created'])); ?></td>
        </tr>
        <tr>
            <td>Author : </td>
            <td><?= htmlspecialchars($post['author']); ?></td>
        </tr>
        <tr>
            <td colspan="2"> <a href="/posts/">Back to Posts</a></td>
        </tr>
    </table>
<?php else: ?>
    <p>No Post Found</p>
<?php endif; ?>
</body>
</html>