<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 14px;
        }
        h1 {
            color: red;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 50px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>
<body>
<h1>Application Errors</h1>
<div></div>
<?php if (isset($error)) : ?>
    <h2>Error : <?= htmlspecialchars($error); ?>!</h2>
<?php else: ?>
    <p>No errors found.</p>
<?php endif; ?>
</body>
</html>